### ISSUE TITLE
concurrent use of rls-analysis forces a total re-build

### ISSUE THREAD

**Issue by steveklabnik** [nrc/rls-analysis#127]
similar to https://github.com/nrc/rls-analysis/issues/126, if i have VS: Code with rls open in my source tree, but try to use my program on it as well, `cargo check` will do a full re-build, rather than using the existing analysis data. this one seems a bit trickier...

**Comment by nrc** [comment]
I don't think this is an rls-analysis issue since rls-analysis never does any building, it just consumes data. I'm not actually clear on the use case here. Are you doing `cargo check` on the command line as well as using the RLS inside vs code? We deliberately use a different target directory since the RLS compiler is often different from the user's regular compiler and we don't want to force rebuilds for either.

**Comment by steveklabnik** [comment]
> Are you doing cargo check on the command line as well as using the RLS inside vs code?

Sometimes, yeah. I think that we can close this though, as with #126, I wouldn't expect this anyway.
