### ISSUE TITLE
Return an iterator instead of a vector in fn symbols?

### ISSUE THREAD

**Issue by theindigamer** [nrc/rls-analysis#150]
`symbols` returns a vector instead of an iterator. IIUC, if the caller wants to filter on the result, there will be an allocation in the middle which is unnecessary and potentially much larger than the actual dataset that is needed at the end. Would it be okay to change the type signature of this function to return an iterator instead? While I don't see as a bottleneck for anything in particular, it seems like a very minor change as a downstream user can easily add a `.collect()` call to fix their code.

https://github.com/nrc/rls-analysis/blob/851eb05e9606170c203e5f724db5a3d23aacbbe0/src/lib.rs#L448-L458

I tried actually making this change just to see whether it would work but got ~~strange errors in compiling `proc-macro2`, which seems to be due to a wrong nightly version of the compiler.~~ a bunch of lifetime errors due to the lambdas. I'm not sure if there is a way to work around them/emulate Python style `yield` in Rust.

**Comment by nrc** [comment]
I don't think this is possible, because of the closures we don't have anything to iterate over with a lifetime longer than the function. The best we could do is to take a closure supplied by the user which gives an iterator as its argument. However, that is a larger change for clients, so I think we should only do that if necessary and/or supply it as well as this function (note that this function could easily be implemented in terms of the other, so we wouldn't dup any code).

**Comment by theindigamer** [comment]
Yeah, that makes sense, I initially thought it might be a small change, I was wrong there.
