### ISSUE TITLE
Is a cargo project required to read the analysis data?

### ISSUE THREAD

**Issue by euclio** [nrc/rls-analysis#76]
I’m trying to generate and load save-analysis data for a single file without invoking cargo.

Here’s what I have so far:

crate_doc.rs:

```rust
#![crate_type = "lib"]

//! Docs.
```

```sh
$ rustc -Z save-analysis crate_doc.rs
```

This creates a folder save-analysis-temp.

Then, I have

```rust
let host = AnalysisHost::new(Target::Debug);
let path = Path::new("save-analysis-temp");
host.reload(&path, &path, true);
println!("{:?}", host.def_roots().unwrap());
```

However, I don’t see `crate_doc` or `libcrate_doc` in the list of crates printed.

I notice that the only implementor of `AnalysisLoader` is `CargoAnalysisLoader`, which makes me think that this use case is not supported?

**Comment by nrc** [comment]
You probably technically need a Cargo project right now, but it is not an intentional constraint and would be very easy to address. The only reason is that Cargo puts save-analysis in a particular place and rls-analysis looks for it there (see https://github.com/nrc/rls-analysis/blob/master/src/lib.rs#L125-L147). All you need to do is implement `iter_paths` differently to point to the right directory (or move the data to the Cargo-expected directory) and then rls-analysis should work.

**Comment by nrc** [comment]
Note that in your example code, the path should point to the root of the cargo project, not to the location of the save-analysis data.
