### ISSUE TITLE
Provide an API to get the visibility of an item

### ISSUE THREAD

**Issue by euclio** [nrc/rls-analysis#79]
I'm not sure if this issue is better suited here or rust-lang/rust, as I'm not sure if this information is in the analysis data.

This is required for steveklabnik/rustdoc, so we can only document public items.

cc https://github.com/steveklabnik/rustdoc/issues/7

**Comment by nrc** [comment]
By using a config (see https://github.com/nrc/rls-data/blob/master/src/config.rs) you can request only public items from save-analysis. I think this solves your problem without needing visibility in the analysis data. However, I think it is not quite what you want - you want 'visible' items, not public ones (i.e., a public item in a non-public module should not be included). This needs fixing in the save-analysis crate of the compiler. (I think you may also need to take into account `pub use`, which is a bit more complicated).

So, why not include visibility info in save-analysis? Basically because it is usually not what you want, you want to know whether an item is visible from a certain place in the code, and the `pub` annotation is not enough to tell you that - you need the modules, plus the algorithm used. IMO that should stay in the compiler. Given that the answer depends on 'where it is asked' it seems like not a suitable thing to have in save-analysis (also, it is something that IDEs never use).

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/43521 was fixed five days ago, so this should be unblocked?

**Comment by euclio** [comment]
Yep, this should be closed.
